### ISSUE TITLE
firebase Project

### ISSUE THREAD

**Issue by obaiomari** [ashinga48/React-Native-Firebase-Phone-Authentication#4]
Hello 

at console.firebase, two separate projects should be created for both IOS & android, 
or two apps in one project for ios & android 
or only a project with one app for web

one more thing:
can your project be applied on this one https://github.com/joinspontaneous/react-native-phone-verification , and if yes how?

please provide the answers or give alternatives, there's nobody all over the network provide a complete example for react native phone authentication 

thank you

**Comment by ashinga48** [comment]
Hey @obaiomari, 

you should setup your authentication settings in console of firebase ( two apps in one project for ios & android ).

-- About Integration (not sure you should be ok integrating with it). 

Anyways, thanks for reminding. I am now creating a video tutorial for this and even update the plugin code. 

will post back the process tutorial.

Thanks.

**Comment by ManigandanRaamanathan** [comment]
@ashinga48  We need example complete code on integrating this. Will you please share the example code and tutorials.
