### ISSUE TITLE
RNFirebasePhoneAuth.sendOTP got 1 arguments, expected 3

### ISSUE THREAD

**Issue by ZnarKhalil** [ashinga48/React-Native-Firebase-Phone-Authentication#7]
I am trying to get verification code from firebase.
i defined listenToOTP() functions and called it inside componentDidMount function,
now when the user add his phone number and press confirm i call a redux action 
my action is defined in actions file like below:
`export const getCode= (phone) => {
    RNFirebasePhoneAuth.sendOTP(phone);
   };` 
but i get an error RNFirebasePhoneAuth.sendOTP got 1 arguments, expected 3

any help please?

**Comment by ashinga48** [comment]
Oops I forgot to remove the unnecessary functions on the native side. it's due to that. 

you can just pass empty functions

```
RNFirebasePhoneAuth.sendOTP(phoneNumber, ()=> {},()=> {});
```

**Comment by ZnarKhalil** [comment]
Thank you it's working now.

**Comment by ManigandanRaamanathan** [comment]
> Oops I forgot to remove the unnecessary functions on the native side. it's due to that.
> 
> you can just pass empty functions
> 
> ```
> RNFirebasePhoneAuth.sendOTP(phoneNumber, ()=> {},()=> {});
> ```

How to verify the received OTP?
